---
_meta:
  type: "internalusers"
  config_version: 2
admin:
  hash: "$2y$12$E7NIyEyuSMtXycA9slxsIOnvcwEQaTb5mfCMArHEvCaUX0PMQ0kOC"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user"
dashboards:
  hash: "$2y$12$E7NIyEyuSMtXycA9slxsIOnvcwEQaTb5mfCMArHEvCaUX0PMQ0kOC"
  backend_roles:
  - "admin"
  - "dashboards"
  opendistro_security_roles:
  - "dashboards"
  description: "User that Dashboard will access OpenSearch"
kibanaserver:
  hash: "$2y$12$E7NIyEyuSMtXycA9slxsIOnvcwEQaTb5mfCMArHEvCaUX0PMQ0kOC"
  reserved: true
  description: "Demo kibanaserver user"