---
_meta:
  type: "internalusers"
  config_version: 2
admin:
  hash: "$2y$12$1qum7MKRsNZXuHh8fw6TDeAU2xsEPgVf8HvLDrhMkSSb.PHxEtldu"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user"
dashboards:
  hash: "$2y$12$1qum7MKRsNZXuHh8fw6TDeAU2xsEPgVf8HvLDrhMkSSb.PHxEtldu"
  backend_roles:
  - "admin"
  - "dashboards"
  opendistro_security_roles:
  - "dashboards"
  description: "User that Dashboard will access OpenSearch"
kibanaserver:
  hash: "$2y$12$1qum7MKRsNZXuHh8fw6TDeAU2xsEPgVf8HvLDrhMkSSb.PHxEtldu"
  reserved: true
  description: "Demo kibanaserver user"